edu-pi/Front

.env
.gitignore
package-lock.json
package.json
src/App.tsx
src/RQProvider.tsx
src/component/CodeEditor.tsx
src/component/IfBox.tsx
src/component/RightSection.tsx
src/main.tsx
src/mocks/handlers.ts
tsconfig.json
vite.config.ts

- #18 
- json에 맞춘 시각화 가장 최신 버전

[#18]feat: json에 맞춘 시각화 가장 최신 버전

---

src/component/CodeEditor.tsx
src/component/ElseBox.tsx
src/component/ForBox.tsx
src/component/IfBox.tsx
src/component/PrintBox.tsx
src/component/RightSection.tsx
src/component/VariableBox.tsx
src/types/activateItem.ts
src/types/elseItem.ts
src/types/forItem.ts
src/types/ifItem.ts
src/types/printItem.ts
src/types/varItem.ts
src/types/variablesItem.ts

close #36 
- 주석 추가와 변수명 변경
-  16335e11764dc86b83ad7dea9e7ba20d2b2e1478 115-117 라인 중점적으로 봐주세요

[#36]feat: 주석 추가와 변수명 변경

---

package-lock.json
package.json
src/component/ForBox.module.css
src/component/ForBox.tsx
src/component/RightSection.tsx
src/main.tsx
src/pages/Home.tsx

- close #38 
- 시각화 앞으로가기 뒤로 가기 기능 추가
- 버튼을 누르면서 리스트에 값이 담기는방식에서 미리 리스트에 전부 값을 다 받아고 앞으로가기 뒤로가기 버튼을 누를 때마다 인덱스의 변화로 시각화가 일어나게 만듬

[#38]feat: 시각화 앞으로가기 뒤로가기 버튼 생성완료

---

src/component/PrintBox.tsx
src/component/RightSection.tsx

- close #32 
- 애니메이션을 주기 위한 애니메이션 라이브러리 framer motion을 적용함
- 박스디자인에 완벽하진 않지만 애니메이션 효과가 들어가게 설정함
- motion framer는 애니메이션 설정에 대한 편의 기능을 제공하는 라이브러리입니다

[#32]feat: 애니메이션을 위한 motion framer 설정 및 적용

---

src/mocks/handlers.ts
src/pages/Home/components/LeftSection/LeftSection.tsx
src/pages/Home/components/LeftSection/components/CodeEditor.module.css
src/pages/Home/components/LeftSection/components/Console.module.css
src/pages/Home/components/LeftSection/components/Console.tsx
src/pages/Home/components/Resizable.module.css
src/pages/Home/components/Resizable.tsx

close #31 
콘솔창에 스크롤을 주어서 콘솔창을 생성 코드 시각화와 연동되는 작업은 추후에 진행
일단은 디자인 생각안하고컴포넌트 위치정도만 잡아뒀습니다

[#31]feat: 콘솔창 띄우기

---

src/pages/Home/components/LeftSection/components/Console.module.css
src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/services/createObjectToAdd.ts
src/pages/Home/types/createDataToAdd/createIfElseChangeDataToAdd.ts
src/pages/Home/types/dataToAdd/codeFlowVariableDataToAdd.ts
src/pages/Home/types/dataToAdd/forDataToAdd.ts
src/pages/Home/types/dataToAdd/ifElseChangeDataToAdd.ts
src/pages/Home/types/dataToAdd/ifElseDataToAdd.ts
src/pages/Home/types/dataToAdd/printDataToAdd.ts

close #60
close #21 
close #51  
- https://github.com/Co-due/Front/pull/59 이 풀리퀘가 conflict수정 과정중에 머지가 되어버려서 따로 이슈를 파서 코드 리뷰수정
- accConsoleLog => curConsoleLog로 수정
- 접두어 create삭제
- 터미널에서 쓰기좋은 Mono체로 콘솔창 글씨체 수정

[#60]fix: 수정못한 코드리뷰에 대한 수정

---

src/App.tsx
src/pages/Home/components/RightSection/components/ElifBox/ElifBox.tsx
src/pages/Login/Login.module.css
src/pages/Login/Login.tsx

- close #62 
- 임시로 사용할 로그인 페이지 작성과 라우팅 처리
- 
- css는 나중에 디자인 나오면 수정할 거여서 안봐도 됩니다

[#62]feat: 임시로 사용할 로그인 페이지 구현 및 라우팅 처리 

---

src/App.css
src/pages/Signup/Signup.tsx

- close #85 
- 회원가입 페이지 디자인 구현
- 전화번호 입력창은 나중에 회의를 통해 디자인 결정나면 적용하겠습니다
- 약관 나오는 기능은 모달창을 구현해야해서 나중에 이슈를 따로 파서 적용하겠습니다

[#85]feat: 회원가입 페이지 디자인 구현

---

src/pages/Home/components/RightSection/RightSection.css
src/pages/Home/components/RightSection/components/ForBox/ForBox.tsx

- close #98 
- while 문 하이라이트 버그 수정과 글씨에 따라 넓이가 줄어드는 거 수정

[#98]fix: while 문 하이라이트 버그 수정과 글씨에 따라 넓이가 줄어드는 거 수정

---

src/App.css
src/mocks/handlers.ts
src/mocks/samples/whileResponseBody.json
src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/components/ElifBox/ElifBox.tsx
src/pages/Home/components/RightSection/components/ForBox/ForBox.tsx
src/pages/Home/components/RightSection/components/WhileBox/WhileBox.tsx
src/pages/Home/components/RightSection/renderingCodeFlow.tsx
src/pages/Home/components/RightSection/services/createObjectToAdd.ts
src/pages/Home/types/codeFlow/whileItem.ts
src/pages/Home/types/dto/ValidTypeDto.ts
src/pages/Home/types/dto/whileDto.ts

- close #87 
- while문 컴포넌트 구현했는데 아직 json데이터가 미완성이라 지금 만들어진 json 데이터까지만 잘돌아가게 만들었습니다
-

[#87]feat: while문 구현

---

src/pages/Home/components/LeftSection/components/Console.module.css
src/pages/Home/components/RightSection/components/PrintBox/PrintBox.module.css
src/pages/Home/components/RightSection/components/PrintBox/PrintBox.tsx

- close #94
- print문의 글씨체가 달라서 나타나는 버그여서 Mono로 변경

[#94]feat: print문 공백 버그 수정 

---

src/pages/Home/components/LeftSection/components/Console.module.css
src/pages/Home/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.module.css
src/pages/Home/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.tsx
src/pages/Home/components/RightSection/components/PrintBox/PrintBox.module.css
src/pages/Home/components/RightSection/components/PrintBox/PrintBox.tsx

- close #91 
- 코드흐름 변수 시각화 위치와 디자인 수정
위치바꿔 봤는데 구체적인 위치는 같이 보면서 조정해보면 좋을 것 같습니다

[#91]feat: 코드흐름 변수 시각화 위치와 디자인 수정

---

package-lock.json
package.json
src/App.css
src/mocks/samples/testResponseBody.json
src/pages/Home/Home.tsx
src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/components/Arrow/Arrow.tsx
src/pages/Home/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.module.css
src/pages/Home/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.tsx
src/pages/Home/components/RightSection/components/ElseBox/ElseBox.tsx
src/pages/Home/components/RightSection/components/ForBox/ForBox.tsx
src/pages/Home/components/RightSection/components/IfBox/IfBox.tsx
src/pages/Home/components/RightSection/components/WhileBox/WhileBox.tsx
src/pages/Home/components/RightSection/renderingCodeFlow.tsx
src/pages/Home/components/RightSection/renderingStructure.tsx
src/pages/Home/types/dataStructureListItem.ts
src/pages/Home/types/dataStructureVarItem.ts
src/pages/Home/types/dto/codeFlowVariableDto.ts
src/pages/Home/types/dto/forDto.ts
src/pages/Home/types/dto/ifElseChangeDto.ts
src/pages/Home/types/dto/ifElseDto.ts
src/pages/Home/types/dto/printDto.ts
src/pages/Home/types/dto/variableDto.ts
src/pages/Home/types/variablesItem.ts
src/pages/Home/types/whileItem.ts
src/store/arrow.ts

- close #97 
-  지금까지 구현된 부분 
- 자료구조 변수, 코드흐름 변수, for, print 는 화살표로 따라가는게 가능
- 테스트 코드로 작성한거라 화살표의 내용이 here이고 나중에 제대로 된 Json이 오면 코드 내용이 잘 반영될 것입니다
- 버그가 있는 부분
- 맨처음 화살표가 생성될 때 최초 위치에서 화살표가 날라온다
- 브라우저 화면이 움직이면 화살표가 고정되어있고 다른 요소하고 같이 안 움직인다

[#97]feat: 시각화하는 부분 따라가는 화살표 구현 

---

src/pages/Home/components/LeftSection/components/CodeEditor.tsx
src/pages/Home/components/RightSection/RightSection.tsx
src/store/editor.ts

- #104 
- 현재 진행 중인 라인에 하이라이트 주는 효과

[#104]feat: 코드에디터에 해당 라인에 하이르트 주는 기능 구현

---

src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/components/WhileBox/WhileBox.tsx
src/pages/Home/components/RightSection/renderingCodeFlow.tsx

- #100 
- while문 안에서 변수를 변화시키는 과정을 만들면 변환과정이 제대로 보이지 않는 버그 수정

[#100]feat: while문 안에서 변수 선언하면 변수의 변환과정이 안보이는 버그 수정

---

src/pages/Home/Home.tsx
src/pages/Home/components/RightSection/RightSection.css
src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/components/ForBox/ForBox.tsx
src/pages/Home/gutter.css

- close #110 
- 코드흐름과 자료구조 시각화 horizontal로 split

[#110]feat: 코드흐름과 자료구조 시각화 horizontal로 split

---

src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/services/addCodeFlow.ts
src/pages/Home/components/RightSection/services/findDeleteUsedId.ts
src/pages/Home/components/RightSection/services/findTargetChild.ts

- close #124 
- for문 한 바퀴돌면 안에 있는 내용 초기화

[#124]feat: for문 한 바퀴돌면 안에 있는 내용 초기화 

---

src/pages/Home/components/LeftSection/components/CodeEditor.tsx
src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/components/ListWrapper/ListWrapper.module.css

[#122]feat: 모나코 에디터 폰트 16으로 변경, 리스트 좌우에 패딩 넣기

---

src/pages/Home/Home.tsx
src/pages/Home/components/RightSection/RightSection.tsx
src/pages/Home/components/RightSection/components/CodeFlowListWrapper/CodeFlowListWrapper.tsx
src/pages/Home/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.tsx
src/pages/Home/components/RightSection/components/ElifBox/ElifBox.tsx
src/pages/Home/components/RightSection/components/ForBox/ForBox.tsx
src/pages/Home/components/RightSection/components/IfBox/IfBox.tsx
src/pages/Home/components/RightSection/renderingCodeFlow.tsx
src/pages/Home/components/RightSection/renderingStructure.tsx

- close #129 
- while문 한바퀴 돌고 안쪽 초기화

[#129]feat: while문 안쪽 한바퀴 돌면 초기화

---

.github/workflows/action.yml
src/App.tsx
src/mocks/handlers.ts
src/pages/Home/Home.tsx
src/pages/Progress/Progress.tsx
src/pages/Visualization/types/codeFlow/printItem.ts
src/pages/components/LoggedInHeader.tsx

- close #144 
진척도 페이지 작성과 헤더와 페이지 연결

[#144]feat: 진척도 페이지 만들고 헤더와 페이지 연결

---

.github/workflows/action.yml
src/App.css
src/App.tsx
src/mocks/handlers.ts
src/pages/Assignment/Assignment.tsx
src/pages/Assignment/components/AssignmentSection.tsx
src/pages/Home/Home.tsx
src/pages/Progress/Progress.tsx
src/pages/Visualization/types/codeFlow/printItem.ts
src/pages/components/LoggedInHeader.tsx

- close #142
화면 크기가 줄면 4줄 정렬에서 3줄 정렬로 변경

[#142]feat: 과제 페이지

---

.github/workflows/action.yml
src/App.css
src/App.tsx
src/index.css
src/mocks/handlers.ts
src/pages/Assignment/Assignment.tsx
src/pages/Assignment/components/AssignmentSection.tsx
src/pages/Group/Group.tsx
src/pages/Group/components/Room.tsx
src/pages/Home/Home.tsx
src/pages/Modify/Modify.tsx
src/pages/Progress/Progress.tsx
src/pages/Visualization/types/codeFlow/printItem.ts
src/pages/components/LoggedInHeader.tsx

- close #140 
그룹방 넓으면 세로 3 좁아지면 세로 2개로 변경되게 만듬
그룹페이지 만들기

[#140]feat: 그룹페이지 만들기

---

__tests__/pages/home/homeUnitTest.test.tsx
src/App.tsx
src/mocks/handlers.ts
src/pages/AuthEmail/AuthEmail.tsx
src/pages/Group/Group.tsx
src/pages/Group/components/Room.tsx
src/pages/Progress/Progress.tsx
src/pages/Signup/components/SignupWrap.tsx
src/pages/Visualization/Visualization.tsx
src/services/api.ts
src/store/mswReady.ts

- #154 
이 그룹페이지에 클래스 정보를 가져오는 api와 그룹을 생성하는 api 연결
그리고 클래스를 눌렀을 때 클래스 주소는 path parmeter로 작업했습니다
```https://github.com/edu-pi/Front/pull/155#issue-2549296975```
이러한 형태로
- 추가적으로 수정할 부분이나 추가하면 좋을 것 같은 기능 있으면 알려주세요

[#154]feat: 클래스 다이나믹 라우팅과 그룹페이지 api 백엔드랑 연결

---

src/mocks/samples/UDFResPiece.ts
src/pages/Visualization/components/LeftSection/components/CodeEditor.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/components/CallUserFuncBox/CallUserFuncBox.tsx
src/pages/Visualization/components/RightSection/components/ReturnBox/ReturnBox.module.css
src/pages/Visualization/components/RightSection/components/ReturnBox/ReturnBox.tsx
src/pages/Visualization/components/RightSection/renderingCodeFlow.tsx
src/pages/Visualization/components/RightSection/services/createObjectToAdd.ts
src/pages/Visualization/types/codeFlow/returnItem.ts
src/pages/Visualization/types/dto/ValidTypeDto.ts
src/pages/Visualization/types/dto/returnDto.ts
src/pages/Visualization/types/dto/variableDto.ts
src/pages/Visualization/types/dto/variablesDto.ts

- ex) #이슈번호, #이슈번호
- return 생성 부분

[#173]feat: return 컴포넌트 생성

---

src/mocks/samples/UDFResPiece.ts
src/pages/Visualization/components/LeftSection/components/GptComment.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.module.css
src/pages/Visualization/components/RightSection/components/CodeFlowVariableBox/CodeFlowVariableBox.tsx
src/pages/Visualization/components/RightSection/services/createObjectToAdd.ts
src/pages/Visualization/types/codeFlow/codeFlowVariableItem.ts
src/pages/Visualization/types/dto/endUserFuncDto.ts
src/pages/Visualization/types/dto/variableDto.ts
src/pages/Visualization/types/dto/variablesDto.ts

- #176 
- return 문 나오면 함수 사라지고 리턴 변수 나타나게 변경

[#176]feat: return 문 나올때 함수 사라지고 return 변수 나타나기

---

package-lock.json
package.json
src/mocks/samples/UDFResPiece.ts
src/mocks/samples/UDFResponseBody.ts
src/pages/Visualization/components/LeftSection/components/CodeEditor.tsx
src/pages/Visualization/components/LeftSection/components/GptComment.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/components/CallUserFuncBox/CallUserFuncBox.tsx
src/pages/Visualization/components/RightSection/components/DefFunctionDataStructure/DefFunctionDataStructure.module.css
src/pages/Visualization/components/RightSection/components/DefFunctionDataStructure/DefFunctionDataStructure.tsx
src/pages/Visualization/components/RightSection/components/ReturnBox/ReturnBox.tsx
src/pages/Visualization/components/RightSection/components/VariableBox/VariableBox.tsx
src/pages/Visualization/components/RightSection/renderingCodeFlow.tsx
src/pages/Visualization/components/RightSection/renderingStructure.tsx
src/pages/Visualization/components/RightSection/services/createObjectToAdd.ts
src/pages/Visualization/components/RightSection/services/unLightCodeFlow.ts
src/pages/Visualization/types/codeFlow/allObjectItem.ts
src/pages/Visualization/types/codeFlow/conditionItem.ts
src/pages/Visualization/types/codeFlow/elseItem.ts
src/pages/Visualization/types/codeFlow/forItem.ts
src/pages/Visualization/types/codeFlow/printItem.ts
src/pages/Visualization/types/codeFlow/returnItem.ts
src/pages/Visualization/types/codeFlow/whileItem.ts
src/pages/Visualization/types/dataStructuresItem/dataStructureVarsItem.ts
src/pages/Visualization/types/dataStructuresItem/warperDataStructureItem.ts
src/pages/Visualization/types/dataToAdd/forDataToAdd.ts
src/pages/Visualization/types/dataToAdd/ifElseDataToAdd.ts
src/pages/Visualization/types/dataToAdd/printDataToAdd.ts
src/pages/Visualization/types/dto/whileDto.ts

- #184 
- 함수 컴포넌트에 isLight boolean 속성 추가

[184]feat: 함수컴포넌트에 isLight boolean 속성 추가

---

src/mocks/samples/UDFResPiece.ts
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/services/LightCodeFlow.ts
src/pages/Visualization/components/RightSection/services/insertEqualToDepth.ts
src/pages/Visualization/components/RightSection/services/insertIntoDepth.ts
src/pages/Visualization/components/RightSection/services/refreshCodeFlow.ts
src/pages/Visualization/components/RightSection/services/unLightCodeFlow.ts
src/pages/Visualization/components/RightSection/services/updateCodeFlow.ts

- #182 
- 함수 흐름에 맞춰서 함수 컴포넌트의 하이라이트가 꺼지게 만들기

[#182]feat: 코드의 진행 흐름에 따라 함수 컴포넌트의 하이라이트가 꺼지게 만들기

---

src/App.css
src/pages/Visualization/components/RightSection/components/DefFunctionDataStructure/DefFunctionDataStructure.tsx
src/pages/Visualization/components/RightSection/components/ListWrapper/ListWrapper.module.css
src/pages/Visualization/components/RightSection/components/ListWrapper/ListWrapper.tsx
src/pages/Visualization/components/RightSection/components/VariableBox/VariableBox.tsx
src/pages/Visualization/components/RightSection/renderingStructure.tsx

[#196]feat: 오른쪽 함수 css 적용

---

src/pages/Signup/components/EmailCheck.css
src/pages/Signup/components/EmailCheck.tsx

- close #205 
- 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)
**전**
**후**

[#205]fix: 이메일 인증페이지 수정

---

src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
src/pages/Visualization/components/LeftSection/components/exampleCode.ts
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #207
- 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[#207]feat: 커리큘럼 코드 추가

---

src/pages/Visualization/Visualization.module.css
src/pages/Visualization/components/LeftSection/LeftSection.module.css
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/RightSection/RightSection.module.css
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #217
- 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[#217]feat: 예외처리 추가

---

src/App.tsx
src/pages/ClassroomDashboard/ClassroomDashboard.tsx
src/pages/Manage/Manage.tsx
src/pages/Manage/components/Guest.tsx
src/pages/Signup/components/EmailCheck.tsx
src/pages/Signup/components/SignupWrap.tsx
src/pages/Visualization/VisualizationClassroom.tsx
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/renderingCodeFlow.tsx
src/pages/components/Header.tsx
src/services/api.ts

- close #216 
- 배포시 console.log 안찍히게 변경
- 클래스 생성 에러 처리
- 시각화 누르고 코드 실행 가능하게 하기
- 회원가입 페이지 모두선택기능 만들기

[#216]배포시 console.log 삭제, 클래스 생성 에러 처리, 시각화 코드 실행 버튼 에러 수정, 회원가입 페이지 모두 선택 버튼 기능 추가

---

src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/CodeEditor.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #228 
- 틀리면 틀린곳 하이라이트 되고 코드 교정 되게 수정

[#228]feat: 틀린곳 하이라이트 안나와서 코드 교정 안되는 버그 수정

---

src/pages/Login/Login.tsx

[#227]feat: 로그인페이지에서 회원가입 페이지로 이동

---

src/App.css
src/pages/Signup/components/SignupWrap.tsx

- close #232
- 이름 필수 입력
- 필수 약관 동의를 체크하지 않은 경우

[#232]feat: 약관 동의를 하지 않으면 버튼 disabled, 이름을 입력하지 않아도 disabled

---

src/pages/components/Header.tsx

[#247] 헤더 정렬

---

src/pages/Visualization/Visualization.tsx

- close #252
- 이번 PR에서 작업한 내용을 간략히 설명해주세요(이미지 첨부 가능)

[#252]fix: 디폴트 코드 수정

---

src/pages/Home/Home.module.css
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #253 
- undefined 버그 수정

[#253]undefined 버그 수정

---

src/pages/Visualization/components/LeftSection/components/Dropdown.tsx

- close #257 
- dropdown 에러 해결

[#257] dropdown 유니크키 생성해서 에러 해결

---

src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/Console.module.css

[#259] 시각화 레이아웃 수정

---

index.html

[#265]feat: 구글 태그 추가

---

src/App.css
src/index.css
src/pages/Classroom/Classroom.tsx
src/pages/ClassroomDashboard/components/GuestRoom.tsx
src/pages/ClassroomDashboard/components/HostRoom.tsx
src/pages/Manage/Manage.tsx
src/pages/Manage/components/Guest.tsx
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/Console.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #271 
- css 수정
- classdashboard 대기인원 삭제

[#271] css 수정과 classdashboard 대기인원 부분 삭제

---

src/pages/Visualization/Visualization.module.css
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/components/LeftSection/LeftSection.module.css
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/Console.module.css
src/pages/Visualization/components/LeftSection/components/Console.tsx
src/pages/Visualization/components/RightSection/RightSection.module.css
src/pages/Visualization/components/RightSection/RightSection.tsx
src/store/console.ts

- close #273 
- 콘솔에 정보가 남아있는 상태에서 나갔다 들어와도 콘솔에 정보가 남아있는 버그 수정
- 전체적으로 시각화 창 ui가 깨지는 css 수정

[#273]fix: 콘솔에 남아있는 정보 나갔다 들어오면 초기화 되게 변경

---

src/App.css
src/pages/Visualization/Visualization.tsx

- close #263 
- 시각화 사용법을 보여주는 노션 링크 추가

[#263]feat: 시각화 사용법 기능 추가

---

src/App.css
src/index.css
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/components/LeftSection/LeftSection.module.css
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/renderingCodeFlow.tsx
src/pages/Visualization/components/RightSection/renderingStructure.tsx

- close #275 
- 코드시각화 변수시각화 부분 스크롤 움직여도 화살표 붙게 변경
- 전체적인 레이아웃도 맞춰지게 수정

[#275]feat: 안쪽에 스크롤 생길때 화살표 리렌더링 터지게 하기

---

src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/Console.tsx
src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #277
**~~예시, 샘플, 튜토리얼 sample code(유진)~~**
**~~“코드작성” -> “코드 작성” (유진)~~
~~console -> 콘솔, 실행창 (유진)~~**
**~~“input”을입력해주세여 -> 변수를 입력해주세요(유진) → input()을 사용하는 경우 입력해주세요.~~**
**~~“코드실행” -> 실행결과, 결과보기(유진)~~**

[#277]fix: 멘토님 피드백 CSS 수정

---

src/pages/Visualization/components/LeftSection/LeftSection.module.css
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/RightSection/RightSection.module.css
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #280 
- 코드 실행 버튼 RightSection으로 이동

[#280]feat: 코드 실행 버튼 RightSection으로 이동

---

src/pages/Classroom/Classroom.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #282 
- stepIdx가 초기화가 되지 않아서 잘못된 index접근 에러가 발생함 
- 페이지를 나갈때 stepIdx를 0으로 초기화시켜서 에러 해결

[#282]feat: 시각화창에서 시각화 누르고 다른페이지갔다가 돌아오면 버그생기는 에러 해결

---

src/pages/Visualization/Visualization.tsx
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/GptComment.tsx
src/pages/components/CustomAlert.tsx

- close #285
- gpt기능 예외처리해서 상황에 맞춰서 Alert띄어주게 변경
- customAlert가 처음 등장할때 렌더링이 3번씩 터지는 버그 수정
- 제대로 교정이 안되는 건 gpt 문제 주석이 나오면 gpt의 정확도가 떨어지는 것 같음

[#285] gpt예외처리, customAlert 렌더링이 3번씩 터지는 버그 수정 

---

src/index.css
src/pages/Visualization/Visualization.module.css
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/VisualizationClassroom.tsx

[#288]메인 페이지 css 수정 

---

src/index.css
src/pages/ClassroomDashboard/components/HostRoom.tsx
src/pages/Visualization/Visualization.module.css
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/VisualizationClassroom.tsx

front deploy

---

src/App.css
src/App.tsx
src/pages/Classroom/Classroom.tsx
src/pages/Classroom/components/ClassroomModal.module.css
src/pages/Classroom/components/ClassroomModal.tsx
src/pages/Classroom/components/Guest.tsx
src/pages/ClassroomDashboard/ClassroomDashboard.tsx
src/pages/Signup/components/SignupWrap.tsx
src/pages/Visualization/VisualizationClassroom.tsx
src/pages/components/Header.tsx
src/services/api.ts
src/types/apiTypes.ts

[#279]feat: 진척도 페이지 학생 코드 볼 수 있게 하는 기능 추가

---

src/pages/Home/Home.tsx
src/pages/components/Header.tsx

-close #293 
- 시각화 헤더 삭제
- 메인 페이지 link 수정

[#293]fix: 시각화 헤더 삭제 및 메인 link 수정

---

src/App.css
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/VisualizationClassroom.tsx
src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
src/pages/Visualization/components/LeftSection/components/exampleCode.ts

- close #284 
- 입출력 커리큘럼 코드 추가
- 커리큘럼 선택시 시각화, 콘솔 초기화
- 함수 레이아웃 수정

[#284]feat: 입출력 커리큘럼 코드 추가 및 커리큘럼 선택시 시각화, 콘솔 초기화

---

src/App.css
src/pages/Signup/components/SignupWrap.tsx
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/VisualizationClassroom.tsx
src/pages/Visualization/components/LeftSection/components/CodeEditor.tsx
src/pages/Visualization/components/LeftSection/components/Console.module.css
src/pages/Visualization/components/LeftSection/components/Console.tsx
src/pages/Visualization/components/LeftSection/components/GptComment.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/services/isNotServiceDtoType.ts
src/pages/Visualization/context/InputErrorContext.ts
src/services/api.ts
src/store/editor.ts

- close #294  
- input예외처리 
- 시각화 지원하지 않는 타입 블락 
- Gpt파라미터 추가

input예외처리, 시각화 지원하지 않는 타입 블락, Gpt파라미터 추가

---

src/pages/Classroom/Classroom.tsx
src/pages/ClassroomDashboard/ClassroomDashboard.tsx
src/pages/Login/Login.tsx
src/pages/Manage/Manage.tsx
src/pages/Manage/components/Guest.tsx
src/pages/Signup/components/SignupWrap.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx

- close #287 
- 모든 alert 커스텀 alert로 변경

[#287]feat: 모든 alert 커스텀 alert로 변경

---

src/pages/Classroom/components/ClassroomModal.tsx
src/pages/Visualization/VisualizationClassroom.tsx
src/pages/Visualization/components/LeftSection/components/Console.tsx
src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
src/pages/Visualization/components/LeftSection/components/exampleCode.ts
src/pages/Visualization/components/RightSection/RightSection.tsx
src/pages/Visualization/components/RightSection/components/CodeFlowListWrapper/CodeFlowListWrapper.tsx
src/pages/components/Header.tsx

- close #301 
- 커리큘럼 코드 수정 및 리스트 버그 픽스
- 제출 완료 disabled 제거
- 학생 코드 조회 코드가 없을 때 터지지 않게 예외 처리

[#301] 커리큘럼 코드 수정 및 리스트 버그 픽스, 제출 완료 disabled 제거, 코드가 없을 때 터지지 않게 예외 처리

---

package-lock.json
package.json
src/App.css
src/main.tsx
src/pages/Visualization/Visualization.tsx
src/pages/Visualization/components/LeftSection/LeftSection.tsx
src/pages/Visualization/components/LeftSection/components/CodeEditor.tsx
src/pages/Visualization/components/LeftSection/components/Console.module.css
src/pages/Visualization/components/LeftSection/components/Dropdown.tsx
src/pages/Visualization/components/RightSection/RightSection.tsx

[#305]feat: 튜토리얼 기능
